Resources:
  IdeaCommentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ideaId
          AttributeType: S
        - AttributeName: commentId
          AttributeType: S
      KeySchema:
        - AttributeName: ideaId
          KeyType: HASH
        - AttributeName: commentId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.ideaCommentsTableName}