LambdaUploadAvatarFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: "Lambda-UploadAvatarFunctionRole"
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
    Policies:
      - PolicyName: "Lambda-UploadAvatarFunctionRole-Policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:DescribeLogStreams"
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:BatchWriteItem"
                - "s3:PutObject"
                - "s3:PutObjectAcl"
                - "s3:DeleteObject"
                - "s3:PutLifeCycleConfiguration"
              Effect: Allow
              Resource:
                - "arn:aws:logs:*:*:*"
                - "arn:aws:s3:::${self:provider.avatarsStaticBucketName}"
                - "arn:aws:s3:::${self:provider.avatarsStaticBucketName}/*"
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}/*'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}/*'
            - Action:
                - "lambda:InvokeFunction"
              Effect: Allow
              Resource: "*"