service: dailyidea-appsync-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'local'}
  region: ${env:AWS_REGION, 'us-east-1'}


plugins:
  - serverless-offline
  - serverless-appsync-plugin

custom:
  accountId: ${env:AWS_ACCOUNT_ID}
  cogintoUserPoolId: ${env:COGNITO_POOL_ID}
  usersTableName: dailyidea-users-${self:provider.stage}
  ideasTableName: dailyidea-ideas-${self:provider.stage}
  ideasMailBox: ${env:IDEAS_MAILBOX, 'ideas-dev'}
  secretToken: ${env:SECRET_TOKEN, 'secret-tk1x'}
  domainName: ${env:DOMAIN_NAME, 'beta.dailyidea.com'}
  appSync:
    # name:  # defaults to api
    # apiId # only required for update-appsync
    authenticationType: AMAZON_COGNITO_USER_POOLS # API_KEY is also supported
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: ${self:custom.cogintoUserPoolId}
    # mappingTemplatesLocation: # defaults to mapping-templates
    mappingTemplates:
      - dataSource: Ideas
        type: Query
        field: getIdea
        request: "getIdea-request-mapping-template.txt"
        response: "getIdea-response-mapping-template.txt"
      - dataSource: Ideas
        type: Query
        field: ideas
        request: "ideas-request-mapping-template.txt"
        response: "ideas-response-mapping-template.txt"
      - dataSource: Users
        type: Query
        field: meInfo
        request: "meInfo-request-mapping-template.txt"
        response: "meInfo-response-mapping-template.txt"
    # schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: ${self:custom.usersTableName}
          serviceRoleArn: { Fn::GetAtt: [AppSyncServiceRole, Arn] }
      - type: AMAZON_DYNAMODB
        name: Ideas
        description: 'Ideas table'
        config:
          tableName: ${self:custom.ideasTableName}
          serviceRoleArn: { Fn::GetAtt: [AppSyncServiceRole, Arn] }
      - type: AWS_LAMBDA
        name: 'request-link'
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: { Fn::GetAtt: [requestLogin, Arn] }
          serviceRoleArn: { Fn::GetAtt: [AppSyncServiceRole, Arn] }
#            - 'Fn::Join':
#                - ':'
#                - - 'arn:aws:iam'
#                  - Ref: 'AWS::Region'
#                  - Ref: 'AWS::AccountId'
#                  - 'role/Dynamo-${self:custom.appSync.serviceRole}'

functions:
  requestLogin:
    handler: requestLogin.handler
    environment:
      DOMAIN_NAME: ${self:provider.domainName}
      SES_REGION: ${self:provider.region}
      SOURCE_EMAIL: ${self:custom.ideasMailBox}@${self:custom.domainName}
      SECRET_TOKEN: ${self:custom.secretToken}

resources:
  Resources:
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-Lambda-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.usersTableName}'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.usersTableName}/*'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.ideasTableName}'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.ideasTableName}/*'
          - PolicyName: "Lambda-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "arn:aws:lambda:${self:provider.region}:*:function:dailyidea-appsync-backend-${self:provider.stage}-requestLogin"
                    - "arn:aws:lambda:${self:provider.region}:*:function:dailyidea-appsync-backend-${self:provider.stage}-requestLogin:*"
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                  Resource: "*"
