service: serverless-graphql-appsync-dynamo

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'local'}
  region: ${env:AWS_REGION, 'us-east-1'}


plugins:
  - serverless-offline
  - serverless-appsync-plugin

custom:
  accountId: ${env:AWS_ACCOUNT_ID}
  cogintoUserPoolId: ${env:COGNITO_POOL_ID}
  usersTableName: dailyidea-users-${self:provider.stage}
  ideasTableName: dailyidea-ideas-${self:provider.stage}

  appSync:
    # name:  # defaults to api
    # apiId # only required for update-appsync
    authenticationType: AMAZON_COGNITO_USER_POOLS # API_KEY is also supported
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: ${self:custom.cogintoUserPoolId}
    # mappingTemplatesLocation: # defaults to mapping-templates
    mappingTemplates:
      - dataSource: Ideas
        type: Query
        field: getIdea
        request: "getUserInfo-request-mapping-template.txt"
        response: "getUserInfo-response-mapping-template.txt"
      - dataSource: Ideas
        type: Query
        field: ideas
        request: "getUserInfo-request-mapping-template.txt"
        response: "getUserInfo-response-mapping-template.txt"
      - dataSource: Users
        type: Query
        field: meInfo
        request: "meInfo-request-mapping-template.txt"
        response: "meInfo-response-mapping-template.txt"
      - dataSource: Users
        type: Mutation
        field: updateUserInfo
        request: "updateUserInfo-request-mapping-template.txt"
        response: "updateUserInfo-response-mapping-template.txt"
    # schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: ${self:custom.usersTableName}
          serviceRoleArn:
            - 'Fn::Join':
                - ':'
                - - 'arn:aws:iam'
                  - Ref: 'AWS::Region'
                  - Ref: 'AWS::AccountId'
                  - 'role/Dynamo-${self:custom.appSync.serviceRole}'
      - type: AMAZON_DYNAMODB
        name: Ideas
        description: 'Ideas table'
        config:
          tableName: ${self:custom.ideasTableName}
          serviceRoleArn:
            - 'Fn::Join':
                - ':'
                - - 'arn:aws:iam'
                  - Ref: 'AWS::Region'
                  - Ref: 'AWS::AccountId'
                  - 'role/Dynamo-${self:custom.appSync.serviceRole}'

resources:
  Resources:
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Dynamo-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Dynamo-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "dynamodb:Query"
                    - "dynamodb:BatchWriteItem"
                    - "dynamodb:GetItem"
                    - "dynamodb:DeleteItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Scan"
                    - "dynamodb:UpdateItem"
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.usersTableName}'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.usersTableName}/*'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.ideasTableName}'
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:dynamodb'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'table/${self:custom.ideasTableName}/*'
