service: syncService

custom:
  usersTableName: users
  localstack:
    host: http://localhost
    debug: true
    stages:
      - local
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'local'}
  region: ${env:AWS_REGION, 'us-east-1'}

functions:
  preSignUp:
    handler: presignup.handler
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: PreSignUp
  userToDynamoDB:
    handler: cognitoToDDB.handler
    role: CustomUserOnboardingRole
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: PostConfirmation
    environment:
      TABLE_NAME: ${self:custom.usersTableName}
      REGION: ${self:provider.region}

plugins:
  - serverless-localstack
  - serverless-offline

resources:
  - ${file(resources/dynamo-user-table.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
