service: dailyidea-users-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'local'}
  region: ${env:AWS_REGION, 'us-east-1'}
  domainName: ${env:DOMAIN_NAME, 'beta.dailyidea.com'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

custom:
  usersTableName: dailyidea-users-${self:provider.stage}
  ideasMailBox: ${env:IDEAS_MAILBOX, 'ideas-dev'}
  secretToken: ${env:SECRET_TOKEN, 'secret-tk1x'}
  localstack:
    host: http://localhost
    debug: true
    stages:
      - local
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568

functions:
  requestLogin:
    handler: src/requestLogin.handler
    environment:
      DOMAIN_NAME: ${self:provider.domainName}
      SES_REGION: ${self:provider.region}
      SOURCE_EMAIL: ${self:custom.ideasMailBox}@${self:provider.domainName}
      SECRET_TOKEN: ${self:custom.secretToken}
    events:
      - http:
          path: requestLogin
          method: post
          cors: true
  defineAuthChallenge:
    handler: src/defineAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: DefineAuthChallenge
    environment:
      SES_REGION: ${self:provider.region}
  createAuthChallenge:
    handler: src/createAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: CreateAuthChallenge
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendEmail
        Resource: "*"
  verifyAuthChallenge:
    handler: src/verifyAuthChallenge.handler
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: VerifyAuthChallengeResponse
    environment:
      SECRET_TOKEN: ${self:custom.secretToken}
  customMessage:
    handler: src/customMessage.handler
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: CustomMessage
    environment:
      DOMAIN_NAME: ${self:provider.domainName}
  userToDynamoDB:
    handler: src/cognitoToDDB.handler
    role: CustomUserOnboardingRole
    events:
      - cognitoUserPool:
          pool: Daily
          trigger: PostConfirmation
    environment:
      TABLE_NAME: ${self:custom.usersTableName}
      REGION: ${self:provider.region}

plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-prune-plugin

resources:
  - ${file(resources/dynamo-user-table.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
