service: 'dailyidea-mail-processing'

custom:
  serverless-offline:
    port: 4000
#  dynamodb:
#    start:
#      port: 8001
#      inMemory: true
#      migrate: true
  domainName: ${env:DOMAIN_NAME, 'dailidea.net'}
  mailBucket: ${env:SES_BUCKET_NAME, 'dailidea-ses'}
  localstack:
    host: http://localhost
    debug: true
    stages:
      - local
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568

functions:
  processIncomingMail:
    handler: endpoint.endpoint

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-localstack

provider:
  name: 'aws'
  runtime: 'nodejs8.10'
  stage: ${env:STAGE, 'local'}
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    AWS_DEPLOY_REGION: ${self:provider.region}
    SES_S3_BUCKET_NAME: ${self:custom.mailBucket}
    SES_AWS_REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:GetObject
      Resource:
        - { "Fn::GetAtt": ["IdeasTable", "Arn" ] }
        - { "Fn::GetAtt": ["SesEmailStorageS3Bucket", "Arn" ] }
        - { "Fn::Join": [ "/", [
            { "Fn::GetAtt": ["IdeasTable", "Arn" ] }, "index", "userIndex"
          ]]}
        - { "Fn::Join": [ "/", [
            { "Fn::GetAtt": ["IdeasTable", "Arn" ] }, "index", "ideaIndex"
          ]]}

resources:
  - ${file(resources/dynamo-idea-table.yml)}

